version: '2.1'

services:
  api:
    image: vacs-api
    build: ./api
    depends_on:
      - redis
    ports:
      - "80:80"
      - "443:443"
  audiofrontend:
    image: vacs-audiofrontend
    build: ./audiofrontend
    depends_on:
      - api
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    depends_on:
      - api
    ports: 
      - "8181:8181"
      - "9191:9191/udp"
  redis:
    image: redis:6.0-rc1-alpine3.11
