version: '3.3'

services:
  traefik:
    image: traefik:v2.1 # The official v2 Traefik docker image
    command:
      - "--api.insecure=true" # Enables the web UI, Traefik will listen on port 8080 by default for API request.
      - "--providers.docker=true" # tells Traefik to listen to docker
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80" # Traefik will listen to incoming request on the port 80 (HTTP)
    # depends_on:
    #   - landingpage
    #   - soe
    #   - watson_webhook
    ports:
      - "80:80" # The HTTP port
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  soe:
    image: vacs-soe
    build: ./soe
    labels:
      - "traefik.http.routers.seo.entrypoints=web" # Allow request only from the predefined entry point named "web"
      # - traefik.http.routers.soe.rule=Host(`localhost:8000`) # The domain the service will respond to
      - "traefik.http.routers.soe.rule=Path(`/soe`)"
      # - "traefik.enable=true" # Explicitly tell Traefik to expose this container
    depends_on:
      - landingpage
      # - redis
    environment:
      NODE_ENV: production
  watson_webhook:
    image: watson_webhook
    build: ./watson_webhook
    labels:
      - "traefik.http.routers.watson_webhook.entrypoints=web"
      # - traefik.http.routers.watson_webhook.rule=Host(`localhost`)
      - "traefik.http.routers.watson_webhook.rule=Path(`/api/watson_webhook`)"
      # - "traefik.enable=true"
    environment:
      NODE_ENV: production
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    labels:
      - "traefik.http.routers.landingpage.entrypoints=web"
      - "traefik.http.routers.landingpage.rule=Host(`localhost`)"
      - "traefik.http.routers.landingpage.rule=Path(`/`)"
      - "traefik.http.routers.landingpage.middlewares=auth,prefix,cb,landingpagemw"
      - "traefik.http.middlewares.landingpagemw.headers.accesscontrolalloworigin=*"
      - "traefik.http.services.landingpage.loadbalancer.server.port=8181"
      # - "traefik.enable=true"
  # redis:
  #   image: redis:6.0-rc1-alpine3.11
