version: '3.7'

services:
  soe:
    image: vacs-soe
    build: ./soe
#    depends_on:
#      - redis
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    depends_on:
      - soe
    ports: 
      - "8181:8181"
      - "9191:9191/udp"
#  redis:
#    image: redis:6.0-rc1-alpine3.11
