version: '3.3'

services:
  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/var/nginx/error_log.log
      - ./nginx/cache/:/var/nginx/cache
      # - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on: 
      - soe
      - landingpage
      - watson_webhook
  soe:
    image: vacs-soe
    build: ./soe
    depends_on:
      - landingpage
      # - redis
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
  watson_webhook:
    image: watson_webhook
    build: ./watson_webhook
    environment:
      NODE_ENV: production
    ports:
      - "5000:5000"
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    ports:
      - "8181:8181"
      - "9191:9191/udp"
  # redis:
  #   image: redis:6.0-rc1-alpine3.11
