version: '3.7'

services:
  soe:
    image: vacs-soe
    build: ./soe
    depends_on:
      - landingpage
      # - redis
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
      - "443:443"
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    ports:
      - "8181:8181"
      - "9191:9191/udp"
  # redis:
  #   image: redis:6.0-rc1-alpine3.11
