version: '3.7'

services:
  nginx:
    image: nginx:1.17.8-alpine
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/:/var/log/nginx/
      - ./nginx/cache/:/var/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - soe
      - landingpage
  soe:
    image: vacs-soe
    build: ./soe
    depends_on:
      - landingpage
      # - redis
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
  landingpage:
    image: vacs-landingpage
    build: ./landingpage
    ports:
      - "8181:8181"
      - "9191:9191/udp"
  # redis:
  #   image: redis:6.0-rc1-alpine3.11
